export enum APIs {
    FETCH_DATA = 'FETCH_DATA',
    CREATE_USER = 'CREATE_USER',
    MODIFY_USER = 'MODIFY_USER',
    DELETE_USER = 'DELETE_USER',
    SET_TOTAL_DOCS_FOR_SEL = 'SET_TOTAL_DOCS_FOR_SEL',
    SET_API_ERROR = "SET_API_ERROR"
}